### ISSUE TITLE
Updaten corona nieuws

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#1]
**Is your feature request related to a problem? Please describe.**
Nieuws over corona is outdated.

Nieuwe tekst moet worden opgevraagt.

**Comment by saberzero1** [comment]
Ik zal de Ab Actis even informeren hierover.

**Comment by saberzero1** [comment]
Ab Actis heeft aangegeven dat de pagina van het coronanieuw verwijderd mag worden. Ik zal hiervoor vanmiddag een aanpassing pushen.
