### ISSUE TITLE
Veranderen naam Elize

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#103]
Op de openbare website staat Elize nog als Elize van Oostende, maar tegenwoordig heet ze Elize Hummelen-van Oostende. Kan dat veranderd worden?

**Comment by BlockCat** [comment]
@AbactisIU ze kan dit zelf aanpassen.

**Comment by AbactisIU** [comment]
Kun je me dan vertellen waar ik dat kan doen? Ik bedoel namelijk niet het in het besloten gedeelte, maar het openbare (bij het stukje voorstellen van het bestuur)...

**Comment by saberzero1** [comment]
Haar naam in de GezIchthus kan ze zelf wijzigen. Die staat volgens mij nog steeds op van Oostende. De openbare bestuurspagina is nu ook gefixt.

**Comment by BlockCat** [comment]
oh! deze werd bedoeldt! ja oeps.
