### ISSUE TITLE
Opmaak 'Waar wij voor staan' 

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#104]
**Is your feature request related to a problem? Please describe.**
Zoals het nu is, werkt de pagina https://ichthusutrecht.nl/visie-missie, maar mooi is anders. Er zijn veel verschillende lettertypen, de foto is verouderd.

**Describe the solution you'd like**
Ik zou graag zien dat deze pagina geüpdatet wordt naar de huisstijl. Deze kun je vinden op de website.

**Comment by Rogue-Juan** [comment]
Pull request has been made.
