### ISSUE TITLE
Apparaten verwijderen

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#105]
Veel leden loggen met een @ichthusutrecht-mail in op hun telefoon. Nadat de commissie klaar is, hebben ze dan nog steeds toegang tot de Drive (waar gevoelige gegevens opstaan). Is er een manier om het account van hun telefoon te verwijderen?

**Comment by BlockCat** [comment]
Dit is soort van mogelijk, de apparaten voor wie dit mogelijk is zijn verwijderd. En de rest is uitgelogd.
