### ISSUE TITLE
Foto invoegen mededeling BerIchthus

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#114]
**Describe the bug**
Bij het invoegen van een afbeelding bij een mededeling voor in de BerIchthus krijg ik de melding 'Afbeelding is verplicht'. Als ik dan op 'OK' klik, verdwijnt de afbeelding weer. 

**To Reproduce**
1. Ga naar BerIchthus
2. Klik op '+ Beheer mededelingen'
3. Klik op het potloodje bij de mededeling 'Vanuit onze IFES-stafwerker' die aangemaakt is op 2022-11-28
4. Klik op de knop 'Insert image'
5. Selecteer de jpg 'Cees' en druk op 'Open' ![Cees](https://user-images.githubusercontent.com/95128532/204227829-4cc1f351-cea3-442a-9ffc-afb83dbe7d41.jpg)

**Expected behavior**
Ik zou verwachten dat de foto gewoon blijft staan...

**Screenshots**
<img width="876" alt="image" src="https://user-images.githubusercontent.com/95128532/204227308-966e3a96-d00d-4f7e-937d-e85d404348e8.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/95128532/204230038-06c42c97-9c40-4a50-9231-70ff2b4ac5fd.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Firefox
 - Version Chrome: 107.0.5304.107, Firefox: 107.0

**Additional context**

**Comment by BlockCat** [comment]
10mb for post upload is voldoende.
