### ISSUE TITLE
Als ichthiaan wil ik aan kunnen geven hoe handig / leuk een artikel was

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#12]
Wat is een artikel?

**Comment by saberzero1** [comment]
Is dit niet al mogelijk?

> Wat is een artikel?

Ik neem aan een post.

![image](https://user-images.githubusercontent.com/8161064/158028057-23c58ee7-49e2-4244-a4b8-c5da8090eccf.png)
