### ISSUE TITLE
tekstuele aanpassingen

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#120]
https://www.ichthusutrecht.nl/adverteren moet naar email van herus.

Op pagina: https://www.ichthusutrecht.nl/activiteiten-praktisch moet de tekst "Onze oude locatie!" aangepast worden naar "Onze locatie!"

**Comment by Rogue-Juan** [comment]
Zijn gefixt naar wat ik zie.
