### ISSUE TITLE
Ichthus book of Records

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#27]
Als Ichthiaan wil ik records kunnen invoeren op records.ichthusutrecht.nl.

De subdomein moet linken naar: https://www.notion.so/Ichthus-Book-of-Records-560ca3734922425b951565c9c57d7fdd

**Comment by saberzero1** [comment]
Hiervoor moet waarschijnlijk een CNAME record wordt toegevoegd aan de hosting.

**Comment by saberzero1** [comment]
Ik heb het nu met een .htaccess redirect gedaan.
