### ISSUE TITLE
Mededelingen

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#30]
Als Ichtiaan wil ik dat ik een mededeling kan invoeren voor de mededelingen mail (berichthus).

Als communicacie lid wil ik de berichten kunnen redacteren.

**Comment by BlockCat** [comment]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html
https://tiptap.dev/

**Comment by BlockCat** [comment]
xss?

**Comment by saberzero1** [comment]
Volgens mij is dit klaar. Closing issue.
