### ISSUE TITLE
Foutcode bij het verwijderen van sommige oud-leden 

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#52]
Ik ben bezig met het verwijderen van oud-leden en krijg bij sommigen de foutmelding '500 - Server error' te zien, waardoor ik ze niet kan verwijderen (maar wel graag wil verwijderen haha)

**Comment by BlockCat** [comment]
**Analysis:** Some users have created an album, deleting these users result in a key violation: Foreign Key Constraint.

**Solution:** Adjust the user field on the albums table to allow null, and set the field: `ON DELETE SET NULL`
