### ISSUE TITLE
Persoonlijke foto's bestuur veranderen

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#53]
We hebben andere bestuursfoto's die we graag op de website zouden zien bij de persoonlijke stukjes waarin we ons als bestuurslid voorstellen. Deze kan je vinden in de drive van de WebCie/via deze link: https://drive.google.com/drive/folders/1kQC-99Xr-rvOykBw1SLjuraoHdkgy7Hf?usp=sharing 

Verder willen we graag dat de LinkedIn knoppen bij ons persoonlijk doorverwijzen naar onze eigen LinkedIn: 
linkedin.com/in/rebecca-jacobse-046225177
linkedin.com/in/sophie-van-dijk-b361ab174
linkedin.com/in/timo-aalberts-5490b9139
linkedin.com/in/josé-meijer-2471601b8
linkedin.com/in/wietske-jeninga-9363181ba
linkedin.com/in/emma-bout

**Comment by neutron-cracker** [comment]
@AbactisIU Wil je op de [contact pagina](https://ichthusutrecht.nl/contact) ook een verwijzing naar jouw linkedin?

**Comment by AbactisIU** [comment]
> @AbactisIU Wil je op de [contact pagina](https://ichthusutrecht.nl/contact) ook een verwijzing naar jouw linkedin?

oeh dat zou heel chill zijn ja! Graag :)

**Comment by saberzero1** [comment]
Volgens mij is dit al gedaan, closing issue.
