### ISSUE TITLE
Pagina waar alle berichthus mails te zien zijn.

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#60]
Als Ichthiaan wil ik graag alle verzonden berichthus mailtjes kunnen bekijken uit het verleden.

**Comment by BlockCat** [comment]
Er is al functionaliteit dat hiet op lijkt voor beheerders.

**Comment by saberzero1** [comment]
Is dit niet inmiddels klaar, of moeten oude alle bericthhus ook geconvert worden?
