### ISSUE TITLE
pagina titel loopt over

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#61]
Hoi,

ik was aan het rondklikken en kwam dit tegen. De header loopt over in de pagina. Waardoor beide niet fijn lezen.

![image](https://user-images.githubusercontent.com/1307268/149617042-9f00c27e-aee2-45d2-8dcc-cdc43b6c36da.png)

**Comment by saberzero1** [comment]
![image](https://user-images.githubusercontent.com/8161064/155535961-e9862ae1-27c1-4718-88b6-f83c2a6d44f9.png)
![image](https://user-images.githubusercontent.com/8161064/155536119-a3047506-643b-448a-bb85-c44a4d68b8d7.png)
