### ISSUE TITLE
Vragen eerstejaars

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#79]
We gooien er wel een google forms uit aan ichthus ofzo.

**Comment by saberzero1** [comment]
Ik ben van plan er twee forms van te maken:
 - eerste form waar men vragen in kan gooien. Zowel open als meerkeuze vragen.
 - later tweede form waar men kan stemmen op de beste vragen, indien er teveel goede vragen zijn ingediend.

**Comment by saberzero1** [comment]
https://forms.gle/7g5LV17cu9N1Yhtm8 Is dit okay?
