### ISSUE TITLE
Management van agenda

### ISSUE THREAD

**Issue by BlockCat** [ichthus-utrecht/ichthus-website-issues#81]
Als bestuurder zijnde, wil ik de agenda op een handige manier kunnen beheren.

- Beheer agenda in google/microsoft 
- Uploaden van een csv spreadsheet

**Comment by AbactisIU** [comment]
Als nieuwe Ab, ben ik het hier volledig mee eens. Het kost mij vrij veel tijd om de agenda up-to-date te maken. Dat zou ik mijn opvolger graag besparen.

**Comment by BlockCat** [comment]
> Als nieuwe Ab, ben ik het hier volledig mee eens. Het kost mij vrij veel tijd om de agenda up-to-date te maken. Dat zou ik mijn opvolger graag besparen.

Maar hoe!

**Comment by AbactisIU** [comment]
https://support.google.com/calendar/answer/41207?hl=nl
Misschien is dit een idee? Omdat we toch al met google werken, is het misschien een idee om een openbare agenda bij te houden. Google Agenda kan al bestanden uploaden met Excel, en kan geïntegreerd worden in een website...

**Comment by BlockCat** [comment]
> https://support.google.com/calendar/answer/41207?hl=nl Misschien is dit een idee? Omdat we toch al met google werken, is het misschien een idee om een openbare agenda bij te houden. Google Agenda kan al bestanden uploaden met Excel, en kan geïntegreerd worden in een website...

Klinkt als een goed idee!
Mijn voorstel is dan om het als volgt aan te pakken:

1. Gebruik google-calendar api voor agenda (https://developers.google.com/calendar)
2. Combineer met attendees!

**Comment by AbactisIU** [comment]
Ik heb een agenda aangemaakt, wat hebben jullie van mij nodig om die te kunnen integreren?
