### ISSUE TITLE
BerIchthus events verwijzen naar verkeerde plek.

### ISSUE THREAD

**Issue by neutron-cracker** [ichthus-utrecht/ichthus-website-issues#85]
**Describe the bug**
In de BerIchthus staan bovenaan een hele lijst van events. Als je hierop klikt krijg je een 403. 

Ik denk dat het handig is om of een permission toe te voegen voor het bekijken van events, of om door te verwijzen naar de activiteiten pagina op de website, of nog een andere mooie oplossing

**Comment by BlockCat** [comment]
Oplossings richting:
Gebruiker moet event kunnen bekijken.
1. introduceer `events.view` permission
2. alleen voor de view event heb je dan die permissie nodig
3. de rest wel gewoon events.manage
4. tests
5. ???
6. winst
