### ISSUE TITLE
Uploadfunctie voor Bijbelstudies leden

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#87]
Op dit moment is het zo dat leden niet zelf een bijbelstudie kunnen uploaden. Zou dit wel gemaakt kunnen worden? Let wel, alleen bij de map Bijbelstudies, want anders worden alle documenten een chaos haha. Weet niet of dit mogelijk is, maar als het kan zou dat top zijn.

**Comment by saberzero1** [comment]
Misschien meteen ook de folder met recepten openstellen voor uploads. Iets met kookkunst hoog in het vaandel hebben staan enzo.

En wat betreft protocollen uploaden? Ik neem aan dat die uploads via het bestuur lopen? Er is echter nog geen folder voor. Misschien ook nog een folder waar de vis-a-visCie haar uitgaven kan oploaden.

~~@BlockCat weet jij of onze huidige bestandbeheerimplementatie toestaat bepaalde folders open te stellen voor bepaalde gebruikersrollen? Of is het handiger/mogelijk voor nu om de beveiliging van de receptenfolder en bijbelstudiefolder af te halen?~~

Edit: ik zie nu dat we een admin folderbeheerrol hebben en een normale folderbeheerrol. Ik zal die functionaliteit uitbreiden.

**Comment by AbactisIU** [comment]
Het zou zeker fijn zijn als de recepten ook opengesteld worden voor uploads! Protocollen verschijnen volgens mij niet op de website, deze worden ingelijst overhandigd aan het bestuur en niet altijd digitaal doorgestuurd. En folder voor de Vis-à-Vis is denk ik een mooie toevoeging, maar heeft geen grote prioriteit

**Comment by BlockCat** [comment]
Om de visie van Ichthus te bewaken, moet er controle zijn op de bijbelstudies en recepten.
