### ISSUE TITLE
Tijden agenda website

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#92]
Ik heb de events voor september in de agenda gezet, bijvoorbeeld de Introweek. Elke activiteit heb ik via Beheer > Evenementen gezet met een begintijd van 18:00 uur. Op het open gedeelte van de website staan de activiteiten van de introweek echter met een begintijd van 19:00 uur. 
Ik vermoed dat dit een tijdnotatiedingetje is, dat 'ie op GMT staat in plaats van GMT+1...

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlockCat** [comment]
Het is idd een tijdnotatie dingetje. En dan met name wintertijd/zomertijd.

**Comment by BlockCat** [comment]
https://github.com/icthus-utrecht/website/pull/195
