### ISSUE TITLE
Emailadressen commissies

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#93]
Laatst zijn er voor meerdere commissies mailadressen aangemaakt binnen het domein @ichthusutrecht.nl. Daarvoor zou ik graag de naam (dus niet het e-mailadres, maar dat wat je ziet als je je inbox opent als afzender) als volgt willen hebben (incl. hoofdletters):

- [x] Accie@ichthusutrecht.nl met de naam Accie
- [ ] Acquisicie@ichthusutrecht.nl met de naam Acquisicie
- [x] Almanakcie@ichthusutrecht.nl met de naam Almanakcie
- [x] Alumnicie@ichthusutrecht.nl met de naam Alumnicie
- [x] Band@ichthusutrecht.nl met de naam Band Ichthus Utrecht
- [x] Bephenkcie@ichthusutrecht.nl met de naam Bep/Henk-cie
- [x] Diescie@ichthusutrecht.nl met de naam Diecie
- [x] Eerstejaarsweekendcie@ichthusutrecht.nl met de naam Eerstejaarsweekendcie
- [x] Evaluacie@ichthusutrecht.nl met de naam Evaluacie
- [x] Galacie@ichthusutrecht.nl met de naam Galacie
- [x] Graficie@ichthusutrecht.nl met de naam Graficie
- [x] Introducie@ichthusutrecht.nl met de naam Introducie Ichthus Utrecht
- [x] Kerstdinercie@ichthusutrecht.nl met de naam Kerstdinercie
- [x] Maaltijdleiders@ichthusutrecht.nl met de naam Maaltijdleiders
- [x] Missie@ichthusutrecht.nl met de naam Missie
- [ ] Mokcie@ichthusutrecht.nl met de naam MOKcie
- [x] Mteam@ichthusutrecht.nl met de naam M-team
- [ ] Nestoren@ichthusutrecht.nl met de naam Nestoren
- [x] pp@ichthusutrecht.nl met de naam P&P-cie
- [x] Pandcie@ichthusutrecht.nl met de naam Pandcie
- [ ] Passionweek@ichthusutrecht.nl met de naam Passion week
- [ ] Patronustraditum@ichthusutrecht.nl met de naam Patronus traditum
- [ ] Pedelcie@ichthusutrecht.nl met de naam Pedelcie
- [x] Promocie@ichthusutrecht.nl met de naam Promocie
- [x] Shadrackcie@ichthusutrecht.nl met de naam Shadrackcie
- [x] Slotweekendcie@ichthusutrecht.nl met de naam Slotweekendcie
- [x] Sooscie@ichthusutrecht.nl met de naam Sooscie
- [x] Startweekendcie@ichthusutrecht.nl met de naam Startweekendcie
- [x] Studia@ichthusutrecht.nl met de naam StuDIA
- [x] Technicie@ichthusutrecht.nl met de naam Technicie
- [x] Uitweek@ichthusutrecht.nl met de naam UITweek
- [ ] passie@ichthusutrecht.nl met de naam Verdiepingsweekendcie
- [ ] veritasforum@ichthusutrecht.nl met de naam Veritas Forum Ichthus Utrecht
- [x] vis-a-viscie@ichthusutrecht.nl met de naam Vis-á-viscie
- [x] webcie@ichthusutrecht.nl met de naam Webcie
- [ ] Werkgroepstatutenwijziging@ichthusutrecht.nl met de naam Werkgroep statutenwijziging
- [ ] Zokoco@ichthusutrecht.nl met de naam Zokoco

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlockCat** [comment]
Google vereist een voor- en achternaam.
Oplossingsrichting:
Ichthus Utrecht als achternaam

**Comment by BlockCat** [comment]
De volgende mails bestaan niet:
- [Mokcie@ichthusutrecht.nl](mailto:Mokcie@ichthusutrecht.nl)
- [Nestoren@ichthusutrecht.nl](mailto:Nestoren@ichthusutrecht.nl)
- [Passionweek@ichthusutrecht.nl](mailto:Passionweek@ichthusutrecht.nl)
- [Patronustraditum@ichthusutrecht.nl](mailto:Patronustraditum@ichthusutrecht.nl)
- [Pedelcie@ichthusutrecht.nl](mailto:Pedelcie@ichthusutrecht.nl)
- [veritasforum@ichthusutrecht.nl](mailto:veritasforum@ichthusutrecht.nl)
- [Werkgroepstatutenwijziging@ichthusutrecht.nl](mailto:Werkgroepstatutenwijziging@ichthusutrecht.nl)
- [Zokoco@ichthusutrecht.nl](mailto:Zokoco@ichthusutrecht.nl)
De volgende mails moeten nog omgevormd worden tot Gebruiker:
- [Acquisicie@ichthusutrecht.nl](mailto:Acquisicie@ichthusutrecht.nl)
- [passie@ichthusutrecht.nl](mailto:passie@ichthusutrecht.nl)

**Comment by AbactisIU** [comment]
Hoi!
Zou je die mailadressen aan willen maken? En ook de volgende: langetermijnbeleid@ichthusutrecht.nl met de naam Langetermijnbeleid Ichthus Utrecht? Thanks!

**Comment by BlockCat** [comment]
Aangemaakt.
