### ISSUE TITLE
Nieuw postadres

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#96]
Het postadres van Ichthus is gewijzigd. Het nieuwe adres is:
C.S.V. Ichthus Utrecht, Pnyx
Winthontlaan 30C
3526KV Utrecht

Dit moet veranderd worden aan de onderkant van het openbare gedeelte en bij de contactpagina (en alle andere pagina's waar het adres op staat).

**Comment by BlockCat** [comment]
Done
