### ISSUE TITLE
verwijderen lid

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#97]
**Describe the bug**
Bij het verwijderen van twee leden krijg ik de foutmelding: "500 server error"

**To Reproduce**
Ik verwijderde de andere leden via beheer->gebruikers. Dan klikte ik op het prullebakje in dezelfde regel als de naam. Vervolgens kreeg ik bovenin mijn scherm de vraag "Are you sure" en moest ik op OK drukken. 

**Expected behavior**
Bij het verwijderen van andere leden werd ik teruggeleid naar de gebruikerspagina en kreeg ik rechtsonderin de melding Voorbeeldlid is succesvol verwijderd.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version 104.0.5112.81

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbactisIU** [comment]
Het gaat om Daniëlle Bijl en Ingeborg Hakvoort, misschien dat dat helpt...

**Comment by AbactisIU** [comment]
Ik kan ze nog steeds niet verwijderen...

**Comment by Rogue-Juan** [comment]
Fixed by BlockCat.
