### ISSUE TITLE
Bestuurslogo mails

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#98]
**Describe the bug**
In de weergave van de BerIchthus via de website staat in de BerIchthus nog het logo van bestuur Jacobse. Datzelfde geldt voor de preview die ik kan zien via Beheer>E-mail>E-mail>oogje. In de mail die de leden ontvangen staat wel het logo van bestuur Van Hoffen.

**To Reproduce**

**Expected behavior**
Ik zou verwachten dat de preview en de opgeslagen mail exact hetzelfde zijn en het logo van bestuur Van Hoffen hebben, als de mail die daadwerkelijk verzonden wordt.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlockCat** [comment]
Done
