### ISSUE TITLE
 Insturen link berIchthus

### ISSUE THREAD

**Issue by AbactisIU** [ichthus-utrecht/ichthus-website-issues#99]
**Describe the bug**
In de BerIchthus staat bovenaan een knop 'Insturen'. Wanneer je die aanklikt, opent je mailprogramma een e-mail naar communicacie.ichthusutrecht.nl (een mailadres dat we niet meer gebruiken).

**To Reproduce**
zie beschrijving

**Expected behavior**
Er zijn twee mogelijkheden:
- het e-mailadres van de automatisch geopende mail wordt veranderd in abactis@ichthusutrecht.nl
- de knop 'insturen' leidt naar de pagina op de besloten website waar je mededelingen kunt insturen

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlockCat** [comment]
Done
